[project]
name = "pavlov25"
version = "0.1.0"
description = ""
authors = [
    {name = "Clayton Bennett",email = "claytonrobot@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cmd2 (>=2.5.11,<3.0.0)",
    "numpy (>=2.2.3,<3.0.0)",
    "toml (>=0.10.2,<0.11.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
